# Generated by Django 2.2.6 on 2019-10-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
