# Generated by Django 2.2.6 on 2019-10-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0008_auto_20191027_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jirani.Neighbourhood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jirani.Neighbourhood'),
        ),
    ]
