# Generated by Django 2.2.6 on 2019-10-30 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0012_auto_20191029_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updates',
            old_name='tiltle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jirani.Neighbourhood'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jirani.Neighbourhood'),
        ),
    ]
